version: '3.7'

services:
  mongo:
    image: mongo:4.0.12-xenial
    container_name: siosa_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
